#!/bin/bash
fecha=$(date +%y%m%d%H%M%S)

#Setting Up
if [ -n "$2" ];
then
	rm ~/.logs/config
	touch ~/.logs/config
	echo $2 >> ~/.logs/config
	cant=$2	
elif [ ! -e "~/.logs/config" ]; 
then
	cant=$( cat ~/.logs/config)
fi


if [ ! -e "~/.logs/.logception" ];
then
        touch ~/.logs/.logception
fi

if [ ! -d "~/.logs" ];
then
        mkdir -p ~/.logs
fi



currentcant=$(( $(ls ~/.logs | wc -l) -1 ))
echo $currentcant y $cant

#Old

#if [ $cant -eq $currentcant ];
#then
#	file=$(find ~/.logs -type f -name log* -printf '%f\n' | sort | head -n 1)
#	rm ~/.logs/$file
#	echo Borrado
#fi

#Borrado

while [[ "$currentcant" -gt "$((cant - 1))" ]]; do
	echo Borrado
        file=$(find ~/.logs -type f -name log* -printf '%f\n' | sort | head -n 1)
        rm ~/.logs/$file
	echo Borrado $file en $(date +%d-%m-%y) a las $(date +%H:%M:%S)  >> ~/.logs/.logception
	currentcant=$((currentcant - 1))
done

#Comprimido

if [ -d "$1" ];
then
	tar -czf ~/.logs/log_$fecha.tar.gz $1
fi
